version: '3.4'

networks:
  studentappnetwork:  

services:
  studentappDB:
    container_name: studentappDB
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
     - 8002:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=mrpeer123#
    networks:
     - studentappnetwork
