name: Build, Test, and Push images to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

  docker:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker build -t your-docker-image-name:latest .
        docker tag your-docker-image-name:latest your-docker-image-name:$(date +%Y%m%d%H%M%S)

    - name: Log in to Docker Hub (or your container registry)
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker push your-docker-image-name:latest
        docker push your-docker-image-name:$(date +%Y%m%d%H%M%S)
