name: Build & Test 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 📦
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Install dependencies 📂
        run: dotnet restore StudentApp

      - name: Build 🧱
        run: dotnet build StudentApp --configuration Release --no-restore

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # v3.0.0

      - name: Login Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker-compose up --build -d
      
      - name: Push Docker Image in Hub
        run: |
          docker tag studentapp:latest mpeermohideen90/studentapp
          docker push mpeermohideen90/studentapp
